name: Deploy to crates.io

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-deploy-crate
  cancel-in-progress: true

jobs:
  deployment:
    name: "Deploy to crates.io"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Deploy to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_API_TOKEN }}
        run: cargo publish -p kuksa-rust-sdk
